jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        PYTHON_VERSION: '2.7'
      Python34:
        PYTHON_VERSION: '3.4'
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
    displayName: 'Install Python'
  - script: echo hello from Linux
  
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python27:
        PYTHON_VERSION: '2.7'
      Python34:
        PYTHON_VERSION: '3.4'
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
    displayName: 'Install Python'
  - script: echo hello from macOS
  
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        PYTHON_VERSION: '2.7'
      Python34:
        PYTHON_VERSION: '3.4'
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
    displayName: 'Install Python'
  - script: echo hello from Windows
